"""
Джерела Google Таблиць для імпорту каталогу.

Список словників (а не dict з ключами-назвами категорій), щоб кілька
аркушів/різних мапінгів для однієї назви каталогу не затирали одне одного.
"""
from __future__ import annotations

from typing import Any, Dict, Iterator, List, Tuple

CATALOG_SHEET_SOURCES: List[Dict[str, Any]] = [
    {
        "catalog": "Джинси",
        "link": [
            "11uiTW22t3VJtB2bCxeMA2bFPnImGASjPEGt_FUjScc0",
            "168WgtFHOc6CTuFPccqiLO0nQHlsg8sTErzH5_zuDZBI",
        ],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 13,
        "photo": 16,
    },
    {
        "catalog": "Світери",
        "link": [
            "10MTeCvTcGuqqF4MmqGzH8wKu_f4AnVkHaKCDB-fr-Hw",
            "12KrTJoXB0UEHJpTr2lf0TkBABO9IwFa0DBWGr_p6bjA",
        ],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 12,
        "size": 13,
        "photo": 16,
    },
    {
        "catalog": "Взуття весна /осінь",
        "link": ["10z1xV9WBPgktxIjDK6tcdKcUP7WAHrJl_y-id2PGGsg"],
        "sheet": 1,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Взуття зима",
        "link": ["10z1xV9WBPgktxIjDK6tcdKcUP7WAHrJl_y-id2PGGsg"],
        "sheet": 0,
        "title": 6,
        "price": 8,
        "article": 10,
        "size": 11,
        "photo": 14,
    },
    {
        "catalog": "Взуття літо",
        "link": ["10z1xV9WBPgktxIjDK6tcdKcUP7WAHrJl_y-id2PGGsg"],
        "sheet": 2,
        "title": 5,
        "price": 7,
        "article": 8,
        "size": 9,
        "photo": 12,
    },
    {
        "catalog": "Костюми весна /осінь",
        "link": ["1154oTs90EjDFCZ_HlA8TDgZi4VXrrfX5l4rCluTqV3Y"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 14,
        "size": 15,
        "photo": 18,
    },
    {
        "catalog": "Костюми зима",
        "link": ["1154oTs90EjDFCZ_HlA8TDgZi4VXrrfX5l4rCluTqV3Y"],
        "sheet": 1,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Костюми літо",
        "link": ["1154oTs90EjDFCZ_HlA8TDgZi4VXrrfX5l4rCluTqV3Y"],
        "sheet": 2,
        "title": 5,
        "price": 8,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Куртки",
        "link": ["11nhcpsEu3vm-O29MTqaZ18y4VTWgWou2yGAH-Hq2Wa8"],
        "sheet": 0,
        "title": 6,
        "price": 8,
        "article": 11,
        "size": 13,
        "photo": 16,
    },
    {
        "catalog": "Жилетки",
        "link": ["11nhcpsEu3vm-O29MTqaZ18y4VTWgWou2yGAH-Hq2Wa8"],
        "sheet": 1,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 14,
        "photo": 17,
    },
    {
        "catalog": "Штани",
        "link": ["16E75FYRt0_jpGl_0HpWkYIOG293Shnn9Efg5fk36res"],
        "sheet": 0,
        "title": 6,
        "price": 10,
        "article": 12,
        "size": 13,
        "photo": 16,
    },
    {
        "catalog": "Спортивні штани",
        "link": ["18632yyke4WS5vse1Lr4P1ja5o1qjotdkBITld06VaJ4"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Футболки",
        "link": ["10P6KScvz5IanraWPWXS_I-NurJidPxz4KNfIPWSYbKs"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Поло",
        "link": ["10P6KScvz5IanraWPWXS_I-NurJidPxz4KNfIPWSYbKs"],
        "sheet": 1,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Сорочки",
        "link": ["1sA26AXQzWlC6BJuABzAAFIyHd6VydAJ4XB7OZrlcSDQ"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Труси",
        "link": ["13N5RcT5ruOeJMUhyIdrTPYjPPLhe5WljRN014MQ5YkM"],
        "sheet": 0,
        "title": 0,
        "price": 2,
        "article": 4,
        "size": 5,
        "photo": 8,
    },
    {
        "catalog": "Шорти джинсові",
        "link": ["11gIogMqgqHtAIvPZvd173HSuuTSdWeGT7Cwshwg8hMA"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "size": 12,
        "photo": 15,
    },
    {
        "catalog": "Шорти текстильні",
        "link": ["11gIogMqgqHtAIvPZvd173HSuuTSdWeGT7Cwshwg8hMA"],
        "sheet": 1,
        "title": 5,
        "price": 8,
        "article": 10,
        "size": 11,
        "photo": 14,
    },
    {
        "catalog": "Шорти плавальні",
        "link": ["11gIogMqgqHtAIvPZvd173HSuuTSdWeGT7Cwshwg8hMA"],
        "sheet": 2,
        "title": 5,
        "price": 7,
        "article": 9,
        "size": 10,
        "photo": 13,
    },
    {
        "catalog": "Сумки",
        "link": ["1-M9rWFcUneSHvlYxJpmZ81IXVzlRgNHo5Mgn1f9IAHw"],
        "sheet": 0,
        "title": 6,
        "price": 9,
        "article": 11,
        "count": 12,
        "photo": 15,
    },
    {
        "catalog": "Гаманці",
        "link": ["1-M9rWFcUneSHvlYxJpmZ81IXVzlRgNHo5Mgn1f9IAHw"],
        "sheet": 1,
        "title": 6,
        "price": 9,
        "article": 11,
        "count": 12,
        "photo": 17,
    },
    {
        "catalog": "Ремені",
        "link": ["12PRN45-nGEaxr-_qz9oa7Vn69wLZ6T3XmXojeaT4yEY"],
        "sheet": 0,
        "title": 6,
        "price": 8,
        "article": 10,
        "count": 11,
        "photo": 14,
    },
    {
        "catalog": "Кепки",
        "link": ["10CdIbKCZonLf-Yo8SEx5wp97PrJ7ObXNktr_yV1wAbg"],
        "sheet": 0,
        "title": 6,
        "price": 8,
        "article": 10,
        "count": 11,
        "photo": 14,
    },
    {
        "catalog": "Шапки",
        "link": ["10CdIbKCZonLf-Yo8SEx5wp97PrJ7ObXNktr_yV1wAbg"],
        "sheet": 1,
        "title": 6,
        "price": 8,
        "article": 10,
        "count": 11,
        "photo": 14,
    },
    {
        "catalog": "Шкарпетки",
        "link": ["13N5RcT5ruOeJMUhyIdrTPYjPPLhe5WljRN014MQ5YkM"],
        "sheet": 1,
        "title": 0,
        "price": 2,
        "article": 3,
        "count": 4,
        "photo": 7,
    },
]


def get_catalog_sheet_sources() -> List[Dict[str, Any]]:
    return CATALOG_SHEET_SOURCES


def iter_catalog_import_jobs() -> Iterator[Tuple[str, str, Dict[str, Any]]]:
    """(назва каталогу, spreadsheet_id, поля мапінгу колонок без catalog/link)."""
    for item in CATALOG_SHEET_SOURCES:
        catalog_title = item["catalog"]
        fields = {k: v for k, v in item.items() if k not in ("catalog", "link")}
        for spreadsheet_id in item["link"]:
            yield catalog_title, spreadsheet_id, fields
