"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    (os.getenv("DJANGO_SECRET_KEY") or "").strip()
    or "django-insecure-cgd@=k+_ts15&@$5v0-yi31pc*_vde8gn@f*sqe@6e*(i6@x5u"
)


def _env_bool(name: str, default: bool = True) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in ("1", "true", "yes", "on")


# У Docker Compose задайте DJANGO_DEBUG=0 для продакшену
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

# Дозволяє будь-який Host. З DEBUG=False краще перелічити домени явно (не покладайтеся на * у проді).
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3002',
    'http://localhost:8001',
    'https://brandshop.in.ua',
    'http://brandshop.in.ua',
]
CSRF_TRUSTED_ORIGINS += [
    o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Application definition

INSTALLED_APPS = [
     'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    "django_celery_beat",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1",
    'http://localhost:3002',
    'http://localhost:8001'
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = [
    "ngrok-skip-browser-warning",
    'Content-Type',
]
ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Важливо: os.getenv("X", default) НЕ підставляє default, якщо X задано як порожній рядок
# (наприклад POSTGRES_DB= у .env). Тоді Django отримує NAME="" і падає з ImproperlyConfigured.


def _pg_str(name: str, default: str) -> str:
    raw = os.getenv(name)
    if raw is None:
        return default
    stripped = raw.strip()
    return stripped if stripped else default


def _pg_password() -> str:
    """Пароль може бути навмисно порожнім — тоді не підміняємо на default_pass."""
    if "POSTGRES_PASSWORD" not in os.environ:
        return "default_pass"
    return os.environ["POSTGRES_PASSWORD"]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _pg_str('POSTGRES_DB', 'default_db_name'),
        'USER': _pg_str('POSTGRES_USER', 'default_user'),
        'PASSWORD': _pg_password(),
        # У тому ж docker-compose: POSTGRES_HOST=project_db (ім'я сервісу). Зовнішня БД — IP/хост.
        'HOST': _pg_str('POSTGRES_HOST', 'project_db'),
        'PORT': _pg_str('POSTGRES_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uk'  # Українська мова за замовчуванням
USE_I18N = True       # Увімкнення міжнародної локалізації
USE_L10N = True       # Увімкнення локалізації форматів дати та часу
USE_TZ = True         # Використання підтримки часових зон

LANGUAGES = [
    ('uk', 'Українська'),
    ('en', 'English'),
]


TIME_ZONE = 'UTC'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
# Завантаження фото (імпорт, адмінка) йде сюди. За замовчуванням — server/media у репозиторії.
# На проді: DJANGO_MEDIA_ROOT=/var/www/brandshop/media — nginx `location /media/` → `alias` на той самий шлях
# (користувач www-data має читати каталог; не тримайте медіа лише під /root без execute для «інших»).
_media_root_env = os.getenv("DJANGO_MEDIA_ROOT", "").strip()
MEDIA_ROOT = str(Path(_media_root_env).resolve()) if _media_root_env else str(BASE_DIR / "media")

# Абсолютні URL фото/медіа для клієнта (Next.js на іншому домені).
# Приклад: https://brandshop.in.ua — без слешу в кінці. Інакше в serializers лишиться localhost.
PUBLIC_BASE_URL = (
    os.getenv('API_PUBLIC_URL', os.getenv('FILE_HOST', '')).strip().rstrip('/')
)


BOT_TOKEN = os.getenv('BOT_TOKEN')
ADMIN_ID = os.getenv('ADMIN_ID')


# Celery
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
# Celery 6: повтор підключення до брокера на старті (прибирає CPendingDeprecationWarning)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Час для django-celery-beat crontab і Celery beat (за замовчуванням київський)
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'Europe/Kyiv')
# Години щоденного імпорту каталогу з Google Таблиць (локальний час CELERY_TIMEZONE)
CATALOG_SYNC_CRON_HOURS = tuple(
    int(x.strip())
    for x in os.getenv('CATALOG_SYNC_CRON_HOURS', '10,14,18,20').split(',')
    if x.strip()
)