# Generated by Django 5.1 on 2024-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
