# Generated by Django 5.1 on 2024-09-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_property_title_productproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='shop.product'),
        ),
    ]
