# Generated by Django 5.1 on 2024-09-07 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_basketitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='product_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='shop.productproperty'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.productproperty'),
        ),
    ]
