# Generated by Django 5.1 on 2024-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_basketitem_product_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
