# Generated by Django 5.1 on 2024-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
