# Generated by Django 5.1 on 2024-09-16 11:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_catalog_active_product_active_productproperty_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Тип товару', 'verbose_name_plural': 'Типи товарів'},
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='test', max_length=1024, verbose_name='Місто доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='test', max_length=1024, verbose_name='Замовник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'ONLINE'), ('imposed_payment', 'IMPOSED_PAYMENT')], default='online', max_length=20, verbose_name='Оплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='test', max_length=1024, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.CharField(default='test', max_length=1024, verbose_name='Відділення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='catalog_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('cancelled', 'CANCELLED'), ('delivered', 'DELIVERED')], default='pending', max_length=20, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('payed', 'PAYED'), ('cancelled', 'CANCELLED')], default='pending', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Знижка по промокоду'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotion_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Знижка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна кількість товарів'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна зі знижкою'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва типу товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_property_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
