# Generated by Django 5.1 on 2024-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_promocode_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
