# Generated by Django 5.1 on 2024-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_promocode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='value',
            field=models.CharField(default='test', max_length=1024, verbose_name='Промокод'),
            preserve_default=False,
        ),
    ]
