# Generated by Django 5.1 on 2024-09-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_promocode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='photo_banner',
            field=models.ImageField(default=None, upload_to='catalog_photos/', verbose_name='Фото (Всередині каталогу)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='catalog_photos/', verbose_name='Фото (На списку каталогів)'),
        ),
    ]
