# Generated by Django 5.1 on 2024-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_catalog_photo_banner_alter_catalog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productview',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
