# Generated by Django 5.1 on 2024-10-12 07:43

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_basketitem_user_id_alter_order_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Пріоритет'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (На списку каталогів)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo_banner',
            field=models.ImageField(upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (Всередині каталогу)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'ONLINE'), ('imposed_payment', 'IMPOSED_PAYMENT'), ('cryptocurrency', 'CRYPTOCURRENCY')], max_length=20, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('payed', 'PAYED'), ('cancelled', 'CANCELLED'), ('imposed_payment', 'IMPOSED_PAYMENT')], default='pending', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_property_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото'),
        ),
    ]
