# Generated by Django 5.1 on 2024-10-12 13:40

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_catalog_priority_product_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.FileField(upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (На списку каталогів)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo_banner',
            field=models.FileField(upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (Всередині каталогу)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='product_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='product_property_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото'),
        ),
    ]
