# Generated by Django 5.1 on 2024-10-12 13:49

from django.db import migrations

def create_init_banner(apps, schema_editor):
    Banner = apps.get_model("shop", "banner")
    Banner.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_banner'),
    ]

    operations = [
        migrations.RunPython(create_init_banner),
    ]
