# Generated by Django 5.1 on 2024-10-12 18:04

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20241012_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='banner_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Баннер'),
        ),
    ]
