# Generated by Django 5.1 on 2025-01-16 19:58

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (На списку каталогів)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo_banner',
            field=models.FileField(blank=True, null=True, upload_to='catalog_photos/', validators=[shop.validators.validate_image_extension], verbose_name='Фото (Всередині каталогу)'),
        ),
    ]
